services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn dev
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - .git
            - node_modules
        - action: rebuild
          path: package.json
    volumes:
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
      - ./nodemon.json:/app/nodemon.json
      - ./tsconfig.json:/app/tsconfig.json
      - /app/node_modules
    working_dir: /app
    ports:
      - '3001:3001'
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  prisma-studio:
    profiles: ['studio']
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn prisma studio
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    ports:
      - '5555:5555' # Assuming Prisma Studio runs on port 5555
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
    depends_on:
      - db
  prisma-push-schema-to-db:
    profiles: ['db-push']
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn prisma db push --accept-data-loss
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
    depends_on:
      - db
volumes:
  postgres_data:
